# Generated by Django 5.2.12 on 2026-03-12 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='Про нас')),
                ('imgSlider1', models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Перше зображення')),
                ('imgSlider2', models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Друге зображення')),
                ('imgSlider3', models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Третє зображення')),
                ('imgSliderPhone1', models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Перше зображення_телефон')),
                ('imgSliderPhone2', models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Друге зображення_телефон')),
                ('imgSliderPhone3', models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Третє зображення_телефон')),
            ],
            options={
                'verbose_name': 'Інформация Сайта',
                'verbose_name_plural': 'Інформация Сайта',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('slugfilter', models.SlugField(blank=True, max_length=100, unique=True)),
                ('img', models.ImageField(upload_to='uploads/images/')),
                ('imgHold', models.ImageField(blank=True, null=True, upload_to='uploads/images/')),
            ],
            options={
                'verbose_name': 'Фільтри',
                'verbose_name_plural': 'Фільтри',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Галерея сайта',
                'verbose_name_plural': 'Галерея сайта',
            },
        ),
        migrations.CreateModel(
            name='PreviewGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг')),
                ('img', models.ImageField(upload_to='uploads/images/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('about', models.TextField(max_length=512, verbose_name='Опис')),
                ('weight', models.IntegerField(verbose_name='Вага')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('image1', models.ImageField(upload_to='uploads/images/', verbose_name='Зображення_перше')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Зображення_друге')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Зображення_третє')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публікація')),
                ('like', models.IntegerField(default=0, verbose_name='Вподобання')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.filter', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталог',
            },
        ),
        migrations.CreateModel(
            name='GaleriaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='uploads/images/', verbose_name='Фото')),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.galeria', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Фото галереї',
                'verbose_name_plural': 'Фото галереї',
            },
        ),
        migrations.AddField(
            model_name='galeria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerias', to='project.previewgaleria', verbose_name='Категорія'),
        ),
    ]
