# Generated by Django 5.2.12 on 2026-04-26 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва категорії галереї')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-адреса категорії')),
                ('image', models.ImageField(upload_to='uploads/gallery/categories/', verbose_name='Основне зображення категорії')),
                ('hover_image', models.ImageField(blank=True, null=True, upload_to='uploads/gallery/categories/', verbose_name='Зображення при наведенні')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показувати категорію на сайті')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
            ],
            options={
                'verbose_name': 'Категорія галереї',
                'verbose_name_plural': 'Категорії галереї',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='galeriaimage',
            name='galeria',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Інформація сайту', 'verbose_name_plural': 'Інформація сайту'},
        ),
        migrations.AlterModelOptions(
            name='base',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Каталог товарів'},
        ),
        migrations.AlterModelOptions(
            name='filter',
            options={'verbose_name': 'Категорія товарів', 'verbose_name_plural': 'Категорії товарів'},
        ),
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(verbose_name='Текст блоку "Про нас"'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imgSlider1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Перше зображення для слайдера'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imgSlider2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Друге зображення для слайдера'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imgSlider3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Третє зображення для слайдера'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imgSliderPhone1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Перше зображення для телефону'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imgSliderPhone2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Друге зображення для телефону'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imgSliderPhone3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Третє зображення для телефону'),
        ),
        migrations.AlterField(
            model_name='base',
            name='about',
            field=models.TextField(max_length=512, verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='base',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='project.filter', verbose_name='Категорія товару'),
        ),
        migrations.AlterField(
            model_name='base',
            name='image1',
            field=models.ImageField(upload_to='uploads/images/', verbose_name='Перше зображення'),
        ),
        migrations.AlterField(
            model_name='base',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Друге зображення'),
        ),
        migrations.AlterField(
            model_name='base',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Третє зображення'),
        ),
        migrations.AlterField(
            model_name='base',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опублікувати на сайті'),
        ),
        migrations.AlterField(
            model_name='base',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Кількість вподобань'),
        ),
        migrations.AlterField(
            model_name='base',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='base',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-адреса'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='img',
            field=models.ImageField(upload_to='uploads/images/', verbose_name='Зображення категорії'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='imgHold',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Зображення категорії при наведенні'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='slugfilter',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-адреса категорії'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва категорії'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва альбому')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-адреса альбому')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показувати альбом на сайті')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='project.gallerycategory', verbose_name='Категорія галереї')),
            ],
            options={
                'verbose_name': 'Альбом галереї',
                'verbose_name_plural': 'Альбоми галереї',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/gallery/images/', verbose_name='Фото')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='Опис фото для SEO')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.gallery', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фото галереї',
                'verbose_name_plural': 'Фото галереї',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='PreviewGaleria',
        ),
        migrations.DeleteModel(
            name='Galeria',
        ),
        migrations.DeleteModel(
            name='GaleriaImage',
        ),
    ]
