# Generated by Django 5.2.12 on 2026-04-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_gallerycategory_remove_galeria_categoria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
