# Generated by Django 5.2.12 on 2026-05-11 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_delete_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/gallery/images/', verbose_name='Фото')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='Опис фото для SEO')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.gallery', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фото галереї',
                'verbose_name_plural': 'Фото галереї',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
