# Generated by Django 5.2.12 on 2026-07-28 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'ordering': ['-id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Каталог товарів'},
        ),
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['title'], 'verbose_name': 'Категорія товарів', 'verbose_name_plural': 'Категорії товарів'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='imgSliderPhone1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='imgSliderPhone2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='imgSliderPhone3',
        ),
        migrations.RemoveField(
            model_name='base',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='base',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='base',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='img',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='imgHold',
        ),
        migrations.RemoveField(
            model_name='gallerycategory',
            name='hover_image',
        ),
        migrations.AddField(
            model_name='about',
            name='aboutPhoto1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Фото на сторінці "Про нас" 1'),
        ),
        migrations.AddField(
            model_name='about',
            name='aboutPhoto2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Фото на сторінці "Про нас" 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='feature1_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Текст переваги 1'),
        ),
        migrations.AddField(
            model_name='about',
            name='feature1_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Заголовок переваги 1'),
        ),
        migrations.AddField(
            model_name='about',
            name='feature2_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Текст переваги 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='feature2_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Заголовок переваги 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='feature3_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Текст переваги 3'),
        ),
        migrations.AddField(
            model_name='about',
            name='feature3_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Заголовок переваги 3'),
        ),
        migrations.AddField(
            model_name='about',
            name='instagram_post_url',
            field=models.URLField(blank=True, verbose_name='Посилання на пост Instagram для вбудови на сторінці "Про нас"'),
        ),
        migrations.AddField(
            model_name='about',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/the28street/', verbose_name='Посилання на Instagram'),
        ),
        migrations.AddField(
            model_name='about',
            name='stat1_label',
            field=models.CharField(blank=True, max_length=60, verbose_name='Підпис до цифри 1 (напр. "рік заснування")'),
        ),
        migrations.AddField(
            model_name='about',
            name='stat1_value',
            field=models.CharField(blank=True, max_length=20, verbose_name='Цифра 1 (напр. "2021")'),
        ),
        migrations.AddField(
            model_name='about',
            name='stat2_label',
            field=models.CharField(blank=True, max_length=60, verbose_name='Підпис до цифри 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='stat2_value',
            field=models.CharField(blank=True, max_length=20, verbose_name='Цифра 2 (напр. "500+")'),
        ),
        migrations.AddField(
            model_name='about',
            name='stat3_label',
            field=models.CharField(blank=True, max_length=60, verbose_name='Підпис до цифри 3'),
        ),
        migrations.AddField(
            model_name='about',
            name='stat3_value',
            field=models.CharField(blank=True, max_length=20, verbose_name='Цифра 3 (напр. "4.9")'),
        ),
        migrations.AddField(
            model_name='about',
            name='videoSlider1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/', verbose_name='Слайдер (ПК), відео 1 (пріоритетне над фото)'),
        ),
        migrations.AddField(
            model_name='about',
            name='videoSlider2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/', verbose_name='Слайдер (ПК), відео 2 (пріоритетне над фото)'),
        ),
        migrations.AddField(
            model_name='about',
            name='videoSlider3',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/', verbose_name='Слайдер (ПК), відео 3 (пріоритетне над фото)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imgSlider1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Слайдер (ПК), фото 1'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imgSlider2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Слайдер (ПК), фото 2'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imgSlider3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Слайдер (ПК), фото 3'),
        ),
        migrations.AlterField(
            model_name='base',
            name='about',
            field=models.TextField(max_length=512, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='base',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='project.filter', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='base',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубліковано на сайті'),
        ),
        migrations.AlterField(
            model_name='base',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='base',
            name='price',
            field=models.IntegerField(verbose_name='Ціна, грн'),
        ),
        migrations.AlterField(
            model_name='base',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-адреса (slug)'),
        ),
        migrations.AlterField(
            model_name='base',
            name='weight',
            field=models.IntegerField(verbose_name='Вага, г'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='slugfilter',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-адреса (slug)'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-адреса (slug)'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='image',
            field=models.ImageField(upload_to='uploads/gallery/categories/', verbose_name='Основне зображення'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-адреса (slug)'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=150, verbose_name='Опис фото (для SEO)'),
        ),
        migrations.CreateModel(
            name='BaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/images/', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне фото товару')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.base', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товарів',
                'ordering': ['id'],
            },
        ),
    ]
