# Generated by Django 5.2.12 on 2026-07-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_base_options_alter_filter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='stat1_label',
            field=models.CharField(blank=True, max_length=60, verbose_name='Підпис 1 (напр. "рік заснування")'),
        ),
        migrations.AlterField(
            model_name='about',
            name='stat2_label',
            field=models.CharField(blank=True, max_length=60, verbose_name='Підпис 2'),
        ),
        migrations.AlterField(
            model_name='about',
            name='stat3_label',
            field=models.CharField(blank=True, max_length=60, verbose_name='Підпис 3'),
        ),
    ]
